version: "3.9"

services:
  web:
    build: .
    container_name: vetclinic_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./vetclinic:/app
    ports:
      - "8000:8000"
